"""
Counterexample Generation
=========================

This module provides counterexample generation for smart contract
verification, helping developers understand why properties fail.

Features:
- Symbolic counterexample generation
- Concrete counterexample extraction
- Witness generation for violations
- Test case generation

Author: Morpheus Team
"""

from __future__ import annotations
from typing import Dict, List, Optional, Set, Any, Tuple, Callable
from dataclasses import dataclass, field
import z3
import logging

from morpheus.parser.ast import Contract, Function

logger = logging.getLogger(__name__)


@dataclass
class Counterexample:
    """
    Represents a counterexample for a failed proof.
    
    Contains concrete values that violate the property.
    """
    property_name: str
    values: Dict[str, Any] = field(default_factory=dict)
    trace: List[ExecutionStep] = field(default_factory=list)
    description: str = ""
    severity: str = "ERROR"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            'property': self.property_name,
            'values': {k: str(v) for k, v in self.values.items()},
            'trace': [step.to_dict() for step in self.trace],
            'description': self.description,
            'severity': self.severity
        }
    
    def to_test_case(self, language: str = "solidity") -> str:
        """
        Generate a test case from counterexample.
        
        Args:
            language: Target language (solidity, python, etc.)
            
        Returns:
            Test case code as string
        """
        if language == "solidity":
            return self._to_solidity_test()
        elif language == "python":
            return self._to_python_test()
        else:
            return self._to_generic_test()
    
    def _to_solidity_test(self) -> str:
        """Generate Solidity test case."""
        test = f"""// Test case for {self.property_name}
// Generated by Morpheus

contract TestCase {{
    function testCounterexample() public {{
        // Setup values
"""
        for name, value in self.values.items():
            test += f"        uint256 {name} = {value};\n"
        
        test += f"""
        // Execute and check violation
        // Expected: Property {self.property_name} should be violated
    }}
}}
"""
        return test
    
    def _to_python_test(self) -> str:
        """Generate Python test case."""
        test = f"""# Test case for {self.property_name}
# Generated by Morpheus

def test_counterexample():
    # Setup values
"""
        for name, value in self.values.items():
            test += f"    {name} = {value}\n"
        
        test += f"""
    # Execute and check violation
    # Expected: Property {self.property_name} should be violated
    pass
"""
        return test
    
    def _to_generic_test(self) -> str:
        """Generate generic test case."""
        return f"""// Counterexample for {self.property_name}
{self.description}
Values: {self.values}
"""


@dataclass
class ExecutionStep:
    """Represents a step in the execution trace."""
    step_id: int
    operation: str
    pc: int = 0
    values: Dict[str, Any] = field(default_factory=dict)
    storage_snapshot: Dict[str, Any] = field(default_factory=dict)
    stack_snapshot: List[Any] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'step': self.step_id,
            'operation': self.operation,
            'pc': self.pc,
            'values': self.values
        }


class CounterexampleGenerator:
    """
    Generates counterexamples for failed verification conditions.
    
    Uses Z3's model extraction to provide concrete values that
    demonstrate property violations.
    """
    
    def __init__(self):
        self.counterexamples: List[Counterexample] = []
        self.model_history: List[z3.ModelRef] = []
    
    def generate(
        self,
        property_name: str,
        negated_formula: z3.BoolRef,
        solver: z3.Solver,
        context: Dict[str, z3.ExprRef] = None
    ) -> Optional[Counterexample]:
        """
        Generate a counterexample for a failed proof.
        
        Args:
            property_name: Name of the failed property
            negated_formula: Negation of the property formula
            solver: Z3 solver with model
            context: Variable context
            
        Returns:
            Counterexample or None if unsatisfiable
        """
        context = context or {}
        
        # Check if formula is satisfiable
        result = solver.check()
        
        if result != z3.sat:
            return None
        
        model = solver.model()
        self.model_history.append(model)
        
        # Extract concrete values
        values = {}
        for decl in model.decls():
            name = str(decl)
            value = model[decl]
            
            # Convert to Python types
            if isinstance(value, z3.IntNumRef):
                values[name] = value.as_long()
            elif isinstance(value, z3.RatNumRef):
                values[name] = float(value.as_decimal(10))
            elif isinstance(value, z3.BoolRef):
                values[name] = value.bool_value() == z3.Z3_L_TRUE
            else:
                values[name] = str(value)
        
        # Filter out internal Z3 variables
        values = {k: v for k, v in values.items() 
                 if not k.startswith('km!') and not k.startswith('_')}
        
        counterexample = Counterexample(
            property_name=property_name,
            values=values,
            description=f"Counterexample for {property_name}"
        )
        
        self.counterexamples.append(counterexample)
        return counterexample
    
    def generate_with_trace(
        self,
        property_name: str,
        trace: List[ExecutionStep],
        solver: z3.Solver,
        context: Dict[str, z3.ExprRef] = None
    ) -> Optional[Counterexample]:
        """
        Generate counterexample with execution trace.
        
        Args:
            property_name: Name of the failed property
            trace: Execution trace leading to violation
            solver: Z3 solver with model
            context: Variable context
            
        Returns:
            Counterexample with trace or None
        """
        counterexample = self.generate(property_name, z3.BoolVal(True), solver, context)
        
        if counterexample:
            counterexample.trace = trace
        
        return counterexample
    
    def get_all_counterexamples(self) -> List[Counterexample]:
        """Get all generated counterexamples."""
        return self.counterexamples
    
    def clear(self) -> None:
        """Clear all counterexamples."""
        self.counterexamples.clear()
        self.model_history.clear()
    
    def minimize_counterexample(
        self,
        counterexample: Counterexample,
        property_formula: z3.BoolRef
    ) -> Counterexample:
        """
        Minimize counterexample by removing unnecessary values.
        
        Args:
            counterexample: Initial counterexample
            property_formula: Property that is violated
            
        Returns:
            Minimized counterexample
        """
        # Create solver with counterexample values
        solver = z3.Solver()
        
        # Add values as constraints
        for name, value in counterexample.values.items():
            if isinstance(value, bool):
                solver.add(z3.Bool(name) == value)
            else:
                solver.add(z3.BitVec(name, 256) == value)
        
        # Try removing each value
        minimized_values = counterexample.values.copy()
        
        for name in list(minimized_values.keys()):
            # Create solver without this value
            test_solver = z3.Solver()
            for n, v in minimized_values.items():
                if n != name:
                    if isinstance(v, bool):
                        test_solver.add(z3.Bool(n) == v)
                    else:
                        test_solver.add(z3.BitVec(n, 256) == v)
            
            # Check if formula is still satisfied
            test_solver.add(property_formula)
            if test_solver.check() == z3.sat:
                del minimized_values[name]
        
        counterexample.values = minimized_values
        return counterexample


class WitnessGenerator:
    """
    Generates witnesses for verification conditions.
    
    Provides concrete execution traces that demonstrate
    property violations.
    """
    
    def __init__(self):
        self.witnesses: List[Dict[str, Any]] = []
    
    def generate_witness(
        self,
        violation_type: str,
        function: Function,
        counterexample: Counterexample,
        contract: Contract
    ) -> Dict[str, Any]:
        """
        Generate a verification witness.
        
        Args:
            violation_type: Type of violation
            function: Function where violation occurs
            counterexample: Counterexample values
            contract: Contract containing the function
            
        Returns:
            Witness dictionary
        """
        witness = {
            'type': 'verification_witness',
            'format': 'morpheus_v1',
            'violation_type': violation_type,
            'property': counterexample.property_name,
            'function': {
                'name': function.name,
                'contract': contract.name,
                'location': str(function.location) if function.location else 'unknown'
            },
            'input_values': counterexample.values,
            'trace': [step.to_dict() for step in counterexample.trace],
            'description': counterexample.description,
            'recommendation': self._get_recommendation(violation_type)
        }
        
        self.witnesses.append(witness)
        return witness
    
    def _get_recommendation(self, violation_type: str) -> str:
        """Get recommendation for violation type."""
        recommendations = {
            'reentrancy': 'Use checks-effects-interactions pattern or reentrancy guards',
            'overflow': 'Use SafeMath library or Solidity 0.8+ checked arithmetic',
            'access_control': 'Add access control modifiers or require statements',
            'unchecked_call': 'Always check return values of external calls',
            'tx_origin': 'Use msg.sender instead of tx.origin',
            'selfdestruct': 'Add access control to selfdestruct',
            'timestamp': 'Avoid using block.timestamp for critical logic',
        }
        return recommendations.get(violation_type, 'Review and fix the identified issue')
    
    def export_witness(self, filepath: str) -> None:
        """
        Export witnesses to file.
        
        Args:
            filepath: Output file path
        """
        import json
        
        with open(filepath, 'w') as f:
            json.dump({
                'witnesses': self.witnesses
            }, f, indent=2)
    
    def get_witnesses(self) -> List[Dict[str, Any]]:
        """Get all generated witnesses."""
        return self.witnesses


class TestCaseGenerator:
    """
    Generates test cases from counterexamples.
    """
    
    def __init__(self):
        self.test_cases: List[str] = []
    
    def generate_tests(
        self,
        counterexamples: List[Counterexample],
        output_dir: str,
        language: str = "solidity"
    ) -> List[str]:
        """
        Generate test files from counterexamples.
        
        Args:
            counterexamples: List of counterexamples
            output_dir: Output directory
            language: Target language
            
        Returns:
            List of generated file paths
        """
        files = []
        
        for i, ce in enumerate(counterexamples):
            test_code = ce.to_test_case(language)
            
            if language == "solidity":
                filepath = f"{output_dir}/Test{i+1}.sol"
            elif language == "python":
                filepath = f"{output_dir}/test_{i+1}.py"
            else:
                filepath = f"{output_dir}/test_{i+1}.txt"
            
            with open(filepath, 'w') as f:
                f.write(test_code)
            
            files.append(filepath)
            self.test_cases.append(test_code)
        
        return files
    
    def generate_solidity_test_suite(
        self,
        counterexamples: List[Counterexample],
        contract_name: str
    ) -> str:
        """
        Generate a complete Solidity test suite.
        
        Args:
            counterexamples: List of counterexamples
            contract_name: Name of contract under test
            
        Returns:
            Complete test suite code
        """
        suite = f"""// Auto-generated test suite for {contract_name}
// Generated by Morpheus Formal Verification Engine

import "forge-std/Test.sol";
import "../src/{contract_name}.sol";

contract {contract_name}Test is Test {{
"""
        
        for i, ce in enumerate(counterexamples):
            suite += f"""
    function testFuzz_PropertyViolation_{i+1}() public {{
        // Counterexample for: {ce.property_name}
"""
            for name, value in ce.values.items():
                suite += f"        uint256 {name} = {value};\n"
            
            suite += """
        // Execute and verify violation
    }
"""
        
        suite += "}\n"
        return suite
    
    def generate_python_test_suite(
        self,
        counterexamples: List[Counterexample],
        contract_name: str
    ) -> str:
        """
        Generate a complete Python test suite.
        
        Args:
            counterexamples: List of counterexamples
            contract_name: Name of contract under test
            
        Returns:
            Complete test suite code
        """
        suite = f'''"""
Auto-generated test suite for {contract_name}
Generated by Morpheus Formal Verification Engine
"""
import pytest

'''
        
        for i, ce in enumerate(counterexamples):
            suite += f'''
def test_property_violation_{i+1}():
    """Counterexample for: {ce.property_name}"""
'''
            for name, value in ce.values.items():
                suite += f"    {name} = {value}\n"
            
            suite += "    # Execute and verify violation\n    pass\n"
        
        return suite
